version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./DATA:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD
    networks:
      - default
    labels:
      - traefik:enable=false

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    volumes:
      - ./WEB:/var/www/html
      - ./supporting:/scripts
    networks:
      - default
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.backend=$LABEL
      - traefik.docker.network=traefik_default
      - traefik.frontend.rule=Host:$URL

networks:
  default:
    internal: true
  traefik_default:
    external: true
