version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: $DBHOST
      WORDPRESS_DB_USER: $DBUSER
      WORDPRESS_DB_PASSWORD: $DBPASS
      WORDPRESS_DB_NAME: $DBNAME
    volumes:
      - ./WEB:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: $DBUSER
      MYSQL_PASSWORD: $DBPASS
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
